-- Seed initial ball catalog from curated brand data.
-- ON CONFLICT DO NOTHING makes this idempotent on re-run.

insert into public.balls_catalog (brand, model, cover_type, factory_finish, role_tag) values

  -- Storm
  ('Storm', 'Phaze A.I.',       'Pearl Reactive',   'Power Edge',      'strong_asym'),
  ('Storm', 'Equinox',          'Pearl Reactive',   'Power Edge',      'strong_asym'),
  ('Storm', 'Equinox Solid',    'Solid Reactive',   '2000 Grit',       'strong_asym'),
  ('Storm', 'Ion Max Pearl',    'Pearl Reactive',   'Power Edge',      'strong_asym'),
  ('Storm', 'Ion Max',          'Solid Reactive',   '2000 Grit',       'strong_asym'),
  ('Storm', 'Ion Pro Solid',    'Solid Reactive',   'Power Edge',      'strong_asym'),
  ('Storm', 'Ion Pro',          'Hybrid Reactive',  '4000 Grit',       'strong_asym'),
  ('Storm', 'Rocket A.I.',      'Pearl Reactive',   'Power Edge',      'strong_asym'),
  ('Storm', '!Q Tour A.I.',     'Hybrid Reactive',  'Power Edge',      'strong_asym'),
  ('Storm', '!Q Tour Edition',  'Solid Reactive',   '4000 Grit',       'strong_asym'),
  ('Storm', 'Bionic',           'Hybrid Reactive',  '4000 Grit',       'benchmark'),
  ('Storm', 'Monsoon',          'Solid Reactive',   '2000 Grit',       'benchmark'),
  ('Storm', 'Level',            'Solid Reactive',   '1000 Grit',       'benchmark'),
  ('Storm', 'Phaze II',         'Solid Reactive',   '3000 Grit',       'benchmark'),
  ('Storm', 'Hy-Road',          'Hybrid Reactive',  'Reacta Gloss',    'benchmark'),
  ('Storm', 'Next Factor',      'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', 'Identity',         'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', 'Identity B/C/P',   'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', 'Concept',          'Pearl Reactive',   '1000 Grit',       'transition'),
  ('Storm', 'Phaze II Pearl',   'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', 'Hy-Road 40',       'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', 'Road Warrior',     'Pearl Reactive',   'Power Edge',      'transition'),
  ('Storm', '!Q Tour 78/U',     'Urethane',         '500 Grit',        'urethane'),
  ('Storm', 'Pitch Black',      'Urethane',         '1000 Grit',       'urethane'),
  ('Storm', 'Mix',              'Polyester',        'High Gloss',      'spare'),

  -- Roto Grip
  ('Roto Grip', 'Transformer',           'Solid Reactive',  '4000 Abralon',    'strong_asym'),
  ('Roto Grip', 'RST Hyperdrive Pearl',  'Pearl Reactive',  'Power Edge',      'strong_asym'),
  ('Roto Grip', 'RST Hyperdrive',        'Solid Reactive',  '2000 Abralon',    'strong_asym'),
  ('Roto Grip', 'Gremlin Tour-X',        'Hybrid Reactive', '4000 Abralon',    'strong_asym'),
  ('Roto Grip', 'Rockstar',              'Solid Reactive',  '2000 Abralon',    'benchmark'),
  ('Roto Grip', 'Ultimate Wrecker',      'Hybrid Reactive', 'Power Edge',      'benchmark'),
  ('Roto Grip', 'Hustle Earth',          'Solid Reactive',  '2000 Abralon',    'benchmark'),
  ('Roto Grip', 'Hustle X-Ray',          'Solid Reactive',  '4000 Abralon',    'benchmark'),
  ('Roto Grip', 'Gremlin',               'Pearl Reactive',  'Power Edge',      'transition'),
  ('Roto Grip', 'Rockstar Amped',        'Pearl Reactive',  'Power Edge',      'transition'),
  ('Roto Grip', 'Hustle Glow',           'Pearl Reactive',  'Power Edge',      'transition'),
  ('Roto Grip', 'Hustle M-M',            'Pearl Reactive',  'Reacta Gloss',    'transition'),
  ('Roto Grip', 'Jester Clear',          'Polyester',       '3500 Polished',   'spare'),

  -- Hammer
  ('Hammer', 'Black Widow 3.0',            'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Black Widow 3.0 Dynasty',    'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Black Widow Tour V1',        'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Black Widow Mania',          'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Black Widow 2.0 Hybrid',     'Hybrid Reactive', '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Maximum Effect',             'Hybrid Reactive', '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Hammer Effect Tour',         'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', '3-D Offset Assault',         'Solid Reactive',  '500 / 1000 / 2000',    'strong_asym'),
  ('Hammer', 'Zero Mercy Solid',           'Solid Reactive',  '500 / 1000 / 2000',    'benchmark'),
  ('Hammer', 'Hammerhead',                 'Solid Reactive',  '500 / 1000 / 2000',    'benchmark'),
  ('Hammer', 'Anger Solid',                'Solid Reactive',  '500 / 1000 / 2000',    'benchmark'),
  ('Hammer', 'Anger',                      'Solid Reactive',  '1000 / 2000',           'benchmark'),
  ('Hammer', 'Raw Hammer',                 'Solid Reactive',  '2000',                  'benchmark'),
  ('Hammer', 'NU 2.0',                     'Solid Reactive',  '2000',                  'benchmark'),
  ('Hammer', 'Full Effect',                'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Zero Mercy Pearl',           'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Hammerhead Pearl',           'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Bubblegum Vibe',             'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Arctic Vibe',                'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Ocean Vibe',                 'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Hammer Special Effect',      'Pearl Reactive',  'Factory Polish',        'transition'),
  ('Hammer', 'Purple Pearl Urethane',      'Urethane',        '4000 Grit',             'urethane'),
  ('Hammer', 'Purple Pearl Urethane 78D',  'Urethane',        '4000 Grit',             'urethane'),
  ('Hammer', 'Black Pearl Urethane',       'Urethane',        '4000 Grit',             'urethane'),
  ('Hammer', 'Axe',                        'Polyester',       'High Gloss',            'spare'),

  -- Brunswick
  ('Brunswick', 'Energize',            'Hybrid Reactive', '500 / 1000 / 1500 Siaair',  'strong_asym'),
  ('Brunswick', 'Strategy',            'Hybrid Reactive', '500 / 2000 Siaair',          'strong_asym'),
  ('Brunswick', 'Combat Hybrid',       'Hybrid Reactive', '500 / 2000 Siaair',          'strong_asym'),
  ('Brunswick', 'Combat',              'Pearl Reactive',  'Factory Polish',             'strong_asym'),
  ('Brunswick', 'Alert',               'Solid Reactive',  '500 / 1000 / 2000 Siaair',  'benchmark'),
  ('Brunswick', 'Crown Victory Pearl', 'Pearl Reactive',  'Factory Polish',             'transition'),
  ('Brunswick', 'Danger Zone',         'Solid Reactive',  '2000 Siaair',               'benchmark'),
  ('Brunswick', 'Rhino',               'Solid Reactive',  '2000 Siaair',               'benchmark'),
  ('Brunswick', 'Crown 78U',           'Urethane',        '4000 Grit',                 'urethane'),
  ('Brunswick', 'TZone',               'Polyester',       'High Gloss',                'spare'),

  -- Motiv
  ('Motiv', 'Apex Jackal',       'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Jackal Ghost',      'Solid Reactive',  '3000 Grit LSS',             'strong_asym'),
  ('Motiv', 'Jackal Onyx',       'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Evoke Mayhem',      'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Evoke Hysteria',    'Pearl Reactive',  '1500 Micro Pad',            'strong_asym'),
  ('Motiv', 'Primal Ghost',      'Pearl Reactive',  '1500 Micro Pad',            'strong_asym'),
  ('Motiv', 'Lethal Venom',      'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Hyper Venom',       'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Black Venom',       'Solid Reactive',  '500 / 1000 Micro Pad',      'strong_asym'),
  ('Motiv', 'Raptor Reign',      'Solid Reactive',  '2000 Grit LSS',             'strong_asym'),
  ('Motiv', 'Steel Forge',       'Solid Reactive',  '2000 Grit LSS',             'benchmark'),
  ('Motiv', 'Venom Shock',       'Hybrid Reactive', '1000 / 1500 Micro Pad',     'benchmark'),
  ('Motiv', 'Supra Clutch',      'Solid Reactive',  '2000 Grit LSS',             'benchmark'),
  ('Motiv', 'Max Thrill Solid',  'Solid Reactive',  '2000 Grit LSS',             'benchmark'),
  ('Motiv', 'Max Thrill Hybrid', 'Hybrid Reactive', '2000 Grit LSS',             'benchmark'),
  ('Motiv', 'Ascend',            'Solid Reactive',  '2000 Grit LSS',             'benchmark'),
  ('Motiv', 'Nebula',            'Pearl Reactive',  '1500 Micro Pad',            'transition'),
  ('Motiv', 'Venom Hysteria',    'Pearl Reactive',  '1500 Micro Pad',            'transition'),
  ('Motiv', 'Max Thrill Pearl',  'Pearl Reactive',  'Factory Polish',            'transition'),
  ('Motiv', 'Supra Sport',       'Solid Reactive',  '2000 Grit LSS',             'other'),
  ('Motiv', 'Shadow Tank',       'Polyester',       'High Polish',               'spare'),
  ('Motiv', 'Aspire',            'Polyester',       'High Polish',               'spare'),

  -- DV8
  ('DV8', 'Double Trouble',   'Hybrid Reactive', '500 / 1500 Grit',  'strong_asym'),
  ('DV8', 'Dark Side Curse',  'Solid Reactive',  '500 / 1500 Grit',  'strong_asym'),
  ('DV8', 'Severe Collision', 'Hybrid Reactive', '500 / 1500 Grit',  'strong_asym'),
  ('DV8', 'Heckler Hybrid',   'Hybrid Reactive', '1500 Grit',        'benchmark'),
  ('DV8', 'Mantra Solid',     'Solid Reactive',  '1500 Grit',        'benchmark'),
  ('DV8', 'Hater Pearl',      'Pearl Reactive',  'Factory Polish',   'transition'),

  -- Columbia 300
  ('Columbia 300', 'Atlas Hybrid',               'Hybrid Reactive', '500 / 1000 / 1500 Siaair',    'strong_asym'),
  ('Columbia 300', 'Rally',                      'Hybrid Reactive', '500 / 2000 Siaair',            'benchmark'),
  ('Columbia 300', 'Super Cuda PowerCOR Hybrid', 'Hybrid Reactive', '500 / 2000 Siaair',            'benchmark'),
  ('Columbia 300', 'Pulse',                      'Solid Reactive',  '500 / 1500 Siaair',            'benchmark'),
  ('Columbia 300', 'Ricochet Pearl',             'Pearl Reactive',  '500 Siaair / Factory Polish',  'transition'),
  ('Columbia 300', 'Super Cuda PowerCOR Pearl',  'Pearl Reactive',  '500 / 1000 / 1500 Siaair',    'transition'),
  ('Columbia 300', 'Piranha PowerCOR Pearl',     'Pearl Reactive',  'Factory Polish',               'transition'),
  ('Columbia 300', 'White Dot',                  'Polyester',       'High Gloss',                   'spare'),

  -- Radical
  ('Radical', 'Vexed',                    'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Deep Impact',              'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Outer Limits Black Hole',  'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Outer Limits Solid',       'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Evil Eye',                 'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Guru Oracle',              'Hybrid Reactive', '500 / 1000 / 2000',  'strong_asym'),
  ('Radical', 'Torpedo Direct Hit',       'Hybrid Reactive', '1000 / 2000',         'strong_asym'),
  ('Radical', 'Revenge Solid',            'Solid Reactive',  '500 / 1000 / 2000',  'benchmark'),
  ('Radical', 'Intel Recon',              'Hybrid Reactive', '1000 / 2000',         'benchmark'),
  ('Radical', 'No Doubt Solid',           'Solid Reactive',  '500 / 1000 / 2000',  'benchmark'),
  ('Radical', 'Torpedo',                  'Hybrid Reactive', '1000 / 2000',         'benchmark'),
  ('Radical', 'Revenge Pearl',            'Pearl Reactive',  'Factory Polish',      'transition'),

  -- Track
  ('Track', '503A',                  'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Track', '400A Special Edition',  'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Track', '300A',                  'Solid Reactive',  '500 / 1000 / 2000',  'strong_asym'),
  ('Track', '503C',                  'Solid Reactive',  '500 / 1000 / 2000',  'benchmark'),
  ('Track', '300C',                  'Solid Reactive',  '500 / 1000 / 2000',  'benchmark'),
  ('Track', '300C Solid',            'Solid Reactive',  '500 / 1000 / 2000',  'benchmark'),
  ('Track', '503T',                  'Pearl Reactive',  'Factory Polish',      'transition'),
  ('Track', '300T',                  'Pearl Reactive',  'Factory Polish',      'transition'),
  ('Track', 'Kinetic Sapphire Ice',  'Pearl Reactive',  'Factory Polish',      'transition'),
  ('Track', '100P',                  'Polyester',       'High Gloss',          'spare'),

  -- 900 Global
  ('900 Global', 'Origin',    'Hybrid Reactive', 'Power Edge',       'strong_asym'),
  ('900 Global', 'Reality',   'Solid Reactive',  '500 / 2000 Grit',  'strong_asym'),
  ('900 Global', 'Bank Roll', 'Solid Reactive',  '500 / 2000 Grit',  'strong_asym'),
  ('900 Global', 'Zen 25',    'Pearl Reactive',  'Power Edge',       'benchmark'),
  ('900 Global', 'Zen',       'Pearl Reactive',  'Power Edge',       'benchmark'),
  ('900 Global', 'Truth',     'Solid Reactive',  '500 / 2000 Grit',  'benchmark'),
  ('900 Global', 'Network',   'Hybrid Reactive', '1000 / 2000 Grit', 'benchmark'),

  -- Ebonite
  ('Ebonite', 'Spartan',             'Solid Reactive',  '500 / 1000 / 2000 Siaair',  'strong_asym'),
  ('Ebonite', 'Entity',              'Solid Reactive',  '500 / 1000 / 2000 Siaair',  'strong_asym'),
  ('Ebonite', 'The One Ovation',     'Pearl Reactive',  'Factory Polish',             'strong_asym'),
  ('Ebonite', 'Persevere',           'Hybrid Reactive', '500 / 1000 / 2000 Siaair',  'benchmark'),
  ('Ebonite', 'Turbo X',             'Solid Reactive',  '500 / 2000 Siaair',          'benchmark'),
  ('Ebonite', 'Matrix',              'Solid Reactive',  '500 / 2000 Siaair',          'benchmark'),
  ('Ebonite', 'Game Breaker 5 Pearl','Pearl Reactive',  'Factory Polish',             'transition'),
  ('Ebonite', 'Maxim',               'Polyester',       'High Gloss',                 'spare'),

  -- Pyramid
  ('Pyramid', 'King of Diamonds', 'Solid Reactive',  '500 / 2000 Grit',  'strong_asym'),
  ('Pyramid', 'Antidote',         'Hybrid Reactive', '1000 / 2000 Grit', 'benchmark'),
  ('Pyramid', 'Path Rising',      'Pearl Reactive',  'Factory Polish',   'transition'),
  ('Pyramid', 'White Dot',        'Polyester',       'High Gloss',       'spare'),

  -- Lane #1
  ('Lane #1', 'Blazing Inferno', 'Solid Reactive', '500 / 1000 Grit',  'strong_asym'),
  ('Lane #1', 'Firefly',         'Urethane',        '4000 Grit',        'urethane'),
  ('Lane #1', 'Alley Cat',       'Urethane',        '4000 Grit',        'urethane')

on conflict (brand, model) do nothing;
